
var arrLang = {
    'en': {
    'home': 'HOME',
    'about': 'ABOUT',
    'services': 'SERVICES',
	'clients': 'CLIENTS',
	'projects': 'PROJECTS',
	'team': 'TEAM',
	'products': 'PRODUCTS',
    'contact': 'CONTACT US',
    'dsbim': 'SHANGHAI DISAI BIM',
	'company-culture': 'COMPANY CULTURE',
	'company-culture-content':'Focus on BIM and digital design technology to provide each customer with the highest quality, most professional and most satisfactory service.',
	'about-content': 'We focus on providing consulting and implementation of integrated information solutions for enterprises, and are committed to providing advanced and complete BIM/BLM solutions and engineering consulting services to customers in the construction industry to enhance their core competitiveness. The company s aim is to provide each customer with the highest quality, most professional and most satisfactory service. In the field of civil engineering, the company has the BLM/BIM lifecycle implementation capability, providing a full lifecycle solution from design, construction to operation and maintenance management. At the same time, the company has the software secondary development capability based on the mainstream BIM platform, and on this basis formed a series of BIM-based forward design solutions. Since its establishment, the company has been based on honesty and innovation, and has continuously improved its ability to serve customers. So far, it has cooperated with many well-known enterprises at home and abroad, such as: Shanghai Municipal Engineering Design and Research Institute (Group) Co., Ltd., Shanghai Urban Construction Design Research Institute (Group) Co., Ltd., Tongji University Architectural Design and Research Institute ( Group) Co., Ltd., China Design Group Co., Ltd., etc.',
	'services': 'SERVICES',
	'services-content': 'Provides BIM consulting services to customers, involving municipal projects such as buildings, bridges, railways, roads, tunnels, etc.',
	'products-detail-content': 'Through the accumulation of experience, research and development of new products, bringing higher value to customers.',
	'idea': 'IDEA',
	'idea-content': 'To provide each customer with the highest quality, most professional and most satisfactory service.',
	'business': 'BUSINESS',
	'business-content': 'The BLM/BIM lifecycle implementation capability provides a lifecycle solution from design to construction to operation and maintenance management. With secondary development capabilities on the mainstream BIM platform.',
	'municipal-engineering': 'Municipal engineering',
	'municipal-engineering-content': 'Provides BIM consultants for municipal bridges, BIM modeling guidance for various types of bridges,  assist engineers from the Preliminary Design to Construction Drawing Design.',
	'railway': 'Railway',
	'railway-content': 'Based on China Railway Standard Modeling Method, provides standard template library, and helps customers change from traditional 2D design  to 3D design,Improve customer productivity.',
	'building-facade': 'Façade design',
	'building-facade-content': 'Provides consultation for customers on construction, special curtain wall BIM consultation, provide processing and manufacturing data, and assist site construction through BIM technology.',
	'projects-content': 'Our experience is mainly in the field of construction and municipal engineering, including bridges, roads and tunnels.',	
	'projects-all':'ALL',
	'projects-title-bridge':'BRIDGE',
	'projects-title-tunnel':'TUNNEL',
	'projects-title-railway':'RAILWAY',
	'projects-title-road':'ROAD',
	'projects-title-facade':'CURTAIL WALL',	
	'team-content': 'Main personnel introduction',
	'general-manager': 'General manager',
	'general-manager-content': 'More than 12 years of work experience, 8 years of sales experience, He is CEO of the company now.',
	'business-manager': 'Business manager',
	'business-manager-content': 'More than 10 years of work experience, He worked in architectural design units, participated in many large-scale commercial construction projects, and has more than 4 years of experience in municipal engineering BIM project implementation, and also served as the company s business operation management.',
	'project-manager': 'Project manager',
	'project-manager-content': 'More than 8 years of work experience,He worked in architectural design company, participated in many complex modeling of building façade design, with 4 years of municipal engineering BIM project implementation experience',
	'engineer': '3D Modeling Designer',
	'engineer-content': 'More than 3 years of work experience,He is good at parametric models of various bridges, with bridge designers involved in many project design processes',
	'software-development': 'Software development',
	'software-development-content': 'More than 2 years of work experience, focusing on development with 3DEXPERIENCE CATIA software',	
	'experience': 'Experience',
	'experience-project-content': 'Successful project practice',
	'experience-partner-content': 'Friendly partner',
	'experience-base-on-3ds-content': 'Design software based on 3DEXPERIENCE.',
	'experience-open-forums': 'www.3debim.com, an open community forum to provide customers with a better communication platform',
	'dsbim-name':'SHANGHAI DESIGN INFORMATION TECHNOLOGY CO.,LTD',
	'dsbim-address':'Room 202, building 1, Xiexin center, No.2, Lane 187, Xinghong Road, Minhang District, Shanghai, China',
	'dsbim-postnum':' P.C.:200333',
	'dsbim-mainemail':'Email: support@ds-info.cn',
	'3dexperience-bim-forums':'3DEXPERIENCE BIM Forums',
	'3dexperience-bim-forums-links':'3DEXPERIENCE BIM Forums Links',
	'3dexperience-bim-forums-content':'Registering as a member by email, you can ask questions, and you are also welcome to post and discuss technology!',
	'team-01':'Johnny WANG',
	'team-02':'Gang DANG',
	'team-03':'Terrence XU',
	'team-04':'Di LIU',
	'team-05':'Liang TIAN',
	'team-06':'Mark ZHANG',
	'products-detail-content-hbd':'Highway Bridge Design (3DEXPERIENCE Native Apps Application)',
	'products-detail-content-hbd-content':'Based on the design features of China s municipal bridges, a standard template library is created, and the template library is invoked by encapsulating an independent APP to improve the generation efficiency, easy-to-use parameter definition rules, and quick data export.',
	'products-detail-content-rbd':'Railway Bridge Design (3DEXPERIENCE Native Apps Application)',
	'products-detail-content-rbd-content':'Create common templates for railways and develop bridge to quickly prevent the upper and lower structures, while quickly exporting data and importing data to update models.',
	'':''
	
    },
    'chs': {
    'home': '主页',
    'about': '关于我们',
    'services': '服务',
	'clients': '客户',
	'projects': '项目',
	'team': '团队',
	'products': '产品',
	'contact': '联系我们',
	'dsbim': '上海迪赛BIM',
	'company-culture': '企业文化',
	'company-culture-content':'专注BIM与数字化设计技术，为每一位客户提供最优质、最专业、最满意的服务。',
	'about-content': '我们专注于为企业提供整体信息化解决方案咨询和实施，致力于为建筑工程行业客户提供先进而完整的BIM/BLM解决方案和工程咨询服务，以此提升企业核心竞争力。公司的宗旨是：为每一位客户提供最优质、最专业、最满意的服务。 在土木工程领域，公司具有BLM/BIM全生命周期的实施能力，提供从设计、施工到运维管理的全生命周期的解决方案。同时，公司具备基于主流的BIM平台上的软件二次开发能力，并在此基础上形成了一系列基于BIM的正向设计解决方案。 公司成立以来，以诚信为本、创新为魂，不断的提升服务客户的能力。到目前为止已经和国内外众多的知名企业开展合作，例如：上海市政工程设计研究总院（集团）有限公司、上海市城市建设设计研究总院（集团）有限公司、同济大学建筑设计研究院（集团）有限公司、中设设计集团有限公司等。',
	'services': '服务',
	'services-content': '为客户提供BIM咨询服务，涉及建筑、桥梁、铁路、道路、隧道等市政工程.',
	'products-detail-content': '经过经验的积累，研发新的产品，为客户带来更高的价值.',
	'idea': 'IDEA',
	'idea-content': '为每一位客户提供最优质、最专业、最满意的服务.',
	'business': '业务范围',
	'business-content': 'BLM/BIM全生命周期的实施能力，提供从设计、施工到运维管理的全生命周期的解决方案。基于主流的BIM平台上的软件二次开发能力。',
	'municipal-engineering': '市政桥梁',
	'municipal-engineering-content': '为客户提供市政桥梁BIM顾问，各种类型桥梁的BIM建模指导，辅助正向设计，从设计阶段协助工程师，设计制造一体化。',
	'railway': '铁路BIM',
	'railway-content': '基于中国铁路规范，铁路标准建模方法，提供标准模板库，辅助正向设计，帮助客户从传统二维实现三维设计的转变。',
	'building-facade': '建筑幕墙',
	'building-facade-content': '为客户提供前期建筑方案咨询,协助建立参数化模型，异型幕墙BIM咨询，提供加工生产于制造数据，通过BIM技术协助现场施工放样。',
	'projects-content': '我们的经验主要在建筑与市政工程领域，包含桥梁，道路与隧道.',
	'projects-all':'所有',
	'projects-title-bridge':'桥梁',
	'projects-title-tunnel':'隧道',
	'projects-title-railway':'铁路',
	'projects-title-road':'道路',
	'projects-title-facade':'建筑幕墙',
	'team-content': '团队主要人员介绍',
	'general-manager': '总经理',
	'general-manager-content': '超过12年工作经验，具有8年销售经验，现在担任公司业务运行管理',
	'business-manager': '业务经理',
	'business-manager-content': '超过10年工作经验，曾工作于建筑设计单位，参与诸多大型商业建筑项目，具有4年以上市政工程BIM项目实施经验，同时担任公司业务运行管理',
	'project-manager': '项目经理',
	'project-manager-content': '超过8年工作经验，曾工作于建筑设计单位，参与诸多复杂造型的建筑立面设计，具有4年市政工程BIM项目实施经验',
	'engineer': '工程师',
	'engineer-content': '超过3年工作经验，擅长各种桥梁的参数化模型，配合桥梁设计师参与诸多项目设计过程',
	'software-development': '软件开发',
	'software-development-content': '超过2年工作经验，专注与3DEXPERIENCE CATIA软件二次开发',
	'experience': '实践经验',
	'experience-project-content': '成功的项目实践',
	'experience-partner-content': '友好的合作伙伴',
	'experience-base-on-3ds-content': '基于3DEXPERIENCE开发的软件.',
	'experience-open-forums': 'www.3debim.com，开放的社区论坛，为客户提供更好的交流平台',
	'dsbim-name':'上海迪赛信息技术有限公司',
	'dsbim-address':'中国上海市闵行区兴虹路187弄2号协信中心1号楼202室',
	'dsbim-postnum':' 邮编:200333 ',
	'dsbim-mainemail':'电子邮件: support@ds-info.cn',
	'3dexperience-bim-forums':'3DEXPERIENCE BIM 论坛',
	'3dexperience-bim-forums-links': '3DEXPERIENCE BIM 论坛链接',
	'3dexperience-bim-forums-content':'通过邮箱注册成为会员，即可提问，同时也欢迎发帖，交流技术！',
	'team-01':'王 利强',
	'team-02':'党 刚',
	'team-03':'许 松',
	'team-04':'刘 迪',
	'team-05':'田 良',
	'team-06':'张 勇',
	'products-detail-content-hbd':'Highway Bridge Design (3DEXPERIENCE Native Apps Application)',
	'products-detail-content-hbd-content':'基于中国市政桥梁的设计特点，创建了标准模板库，通过封装独立的APP调用模板库，提高生成效率，定义易于使用的参数规则，快速导出数据。',
	'products-detail-content-rbd':'Railway Bridge Design (3DEXPERIENCE Native Apps Application)',
	'products-detail-content-rbd-content':'创建铁路常用的模板，开发出桥梁布跨插件，可以快速防止上部结构与下部结构，同时快速导出数据以及导入数据更新模型。',
	'':''

	
	
    },
    'cht': {
    'home': '主頁',
    'about': '關於我們',
    'services': '服務',
	'clients': '客戶',
	'projects': '項目',
	'team': '團隊',
	'products': '產品',
	'contact': '聯繫我們',
	'dsbim': '上海迪賽BIM',
	'company-culture': '企業文化',
	'company-culture-content':'專注BIM與數字化設計技術，為每一位客戶提供最優質、最專業、最滿意的服務。 ',
	'about-content': '我們專注於為企業提供整體信息化解決方案諮詢和實施，致力於為建築工程行業客戶提供先進而完整的BIM/BLM解決方案和工程諮詢服務，以此提升企業核心競爭力。公司的宗旨是：為每一位客戶提供最優質、最專業、最滿意的服務。在土木工程領域，公司具有BLM/BIM全生命週期的實施能力，提供從設計、施工到運維管理的全生命週期的解決方案。同時，公司具備基於主流的BIM平台上的軟件二次開發能力，並在此基礎上形成了一系列基於BIM的正向設計解決方案。公司成立以來，以誠信為本、創新為魂，不斷的提升服務客戶的能力。到目前為止已經和國內外眾多的知名企業開展合作，例如：上海市政工程設計研究總院（集團）有限公司、上海市城市建設設計研究總院（集團）有限公司、同濟大學建築設計研究院（集團）有限公司、中設設計集團有限公司等。 ',
	'services': '服務',
	'services-content': '為客戶提供BIM諮詢服務，涉及建築、橋樑、鐵路、道路、隧道等市政工程.',
	'products-detail-content': '經過經驗的積累，研發新的產品，為客戶帶來更高的價值.',
	'idea': 'IDEA',
	'idea-content': '為每一位客戶提供最優質、最專業、最滿意的服務.',
	'business': '業務範圍',
	'business-content': 'BLM/BIM全生命週期的實施能力，提供從設計、施工到運維管理的全生命週期的解決方案。基於主流的BIM平台上的軟件二次開發能力。 ',
	'municipal-engineering': '市政橋樑',
	'municipal-engineering-content': '為客戶提供市政橋樑BIM顧問，各種類型橋樑的BIM建模指導，輔助正向設計，從設計階段協助工程師，設計製造一體化。 ',
	'railway': '鐵路BIM',
	'railway-content': '基於中國鐵路規範，鐵路標準建模方法，提供標準模板庫，輔助正向設計，幫助客戶從傳統二維實現三維設計的轉變。 ',
	'building-facade': '建築幕牆',
	'building-facade-content': '為客戶提供前期建築方案諮詢，協助建立參數化模型，異型幕牆BIM諮詢，提供加工生產於製造數據，通過BIM技術協助現場施工放樣。 ',
	'projects-content': '我們的經驗主要在建築與市政工程領域，包含橋樑，道路與隧道.',
	'projects-all':'所有',
	'projects-title-bridge':'橋樑',
	'projects-title-tunnel':'隧道',
	'projects-title-railway':'鐵路',
	'projects-title-road':'道路',
	'projects-title-facade':'建築幕牆',
	'team-content': '團隊主要人員介紹',
	'general-manager': '總經理',
	'general-manager-content': '超過12年工作經驗，具有8年銷售經驗，現在擔任公司業務運行管理',
	'business-manager': '業務經理',
	'business-manager-content': '超過10年工作經驗，曾工作於建築設計單位，參與諸多大型商業建築項目，具有4年以上市政工程BIM項目實施經驗，同時擔任公司業務運行管理',
	'project-manager': '項目經理',
	'project-manager-content': '超過8年工作經驗，曾工作於建築設計單位，參與諸多複雜造型的建築立面設計，具有4年市政工程BIM項目實施經驗',
	'engineer': '工程師',
	'engineer-content': '超過3年工作經驗，擅長各種橋樑的參數化模型，配合橋樑設計師參與諸多項目設計過程',
	'software-development': '軟件開發',
	'software-development-content': '超過2年工作經驗，專注與3DEXPERIENCE CATIA軟件二次開發',
	'experience': '實踐經驗',
	'experience-project-content': '成功的項目實踐',
	'experience-partner-content': '友好的合作夥伴',
	'experience-base-on-3ds-content': '基於3DEXPERIENCE開發的軟件.',
	'experience-open-forums': 'www.3debim.com，開放的社區論壇，為客戶提供更好的交流平台',
	'dsbim-name':'上海迪賽信息技術有限公司',
	'dsbim-address':'中國上海市閔行區興虹路187弄2號協信中心1號樓202室 ',
	'dsbim-postnum':' 郵編:200333 ',
	'dsbim-mainemail':'電子郵件: support@ds-info.cn',
	'3dexperience-bim-forums':'3DEXPERIENCE BIM 論壇',
	'3dexperience-bim-forums-links': '3DEXPERIENCE BIM 論壇鏈接',
	'3dexperience-bim-forums-content':'通過郵箱註冊成為會員，即可提問，同時也歡迎發帖，交流技術！ ',
	'team-01':'王 利強',
	'team-02':'黨 剛',
	'team-03':'許 松',
	'team-04':'劉 迪',
	'team-05':'田 良',
	'team-06':'张 勇',
	'products-detail-content-hbd':'Highway Bridge Design (3DEXPERIENCE Native Apps Application)',
	'products-detail-content-hbd-content':'基於中國市政橋樑的設計特點，創建了標準模板庫，通過封裝獨立的APP調用模板庫，提高生成效率，定義易於使用的參數規則，快速導出數據。 ',
	'products-detail-content-rbd':'Railway Bridge Design (3DEXPERIENCE Native Apps Application)',
	'products-detail-content-rbd-content':'創建鐵路常用的模板，開發出橋樑布跨插件，可以快速防止上部結構與下部結構，同時快速導出數據以及導入數據更新模型。 ',
	'':''


    },
    'jp': {
    'home': 'ホーム',
    'about': '会社案内',
    'services': 'サービス',
	'clients': 'パートナー',
	'projects': '実践プロジェクト',
	'team': 'チーム',
	'products': '製品情報',
    'contact': 'お問い合わせ',
	'dsbim': '上海迪賽BIM',
	'company-culture': '企業文化',
	'company-culture-content':'各顧客に最高品質、最も専門的で最も満足のいくサービスを提供するためのBIMおよびデジタル設計技術に焦点を当てています。 ',
	'about-content': '企業向けの統合情報ソリューションのコンサルティングと実装に重点を置いており、建設業界のお客様に高度で完全なBIM / BLMソリューションとエンジニアリングコンサルティングサービスを提供して、コア競争を強化しています。力。同社の目的は、各顧客に最高品質で最もプロフェッショナルで満足のいくサービスを提供することです。土木工学の分野では、同社はBLM / BIMライフサイクル実装機能を備えており、設計、建設から運用、保守管理までの完全なライフサイクルソリューションを提供します。同時に、同社は主流のBIMプラットフォームに基づくソフトウェアの二次開発機能を備えており、これに基づいて一連のBIMベースのフォワードデザインソリューションを形成しました。設立以来、同社は誠実さと革新に基づいており、顧客へのサービス能力を継続的に向上させてきました。これまで、国内外の多くの有名企業と協力してきました。例えば、上海市政工程設計研究總院（集團）有限公司、上海市城市建設設計研究總院（集團）有限公司、同濟大學建築設計研究院（集團）有限公司、中設設計集團有限公司' ,
	'services': 'サービス',
	'services-content': '建物、橋、鉄道、道路、トンネルなどの自治体プロジェクトを含む、クライアント向けのBIMコンサルティングサービスを提供します.',
	'products-detail-content': '新しい製品の経験、研究開発の蓄積の後、顧客により高い価値をもたらします.',
	'idea': 'IDEA',
	'idea-content': '各顧客に最高品質、最も専門的で最も満足のいくサービスを提供する.',
	'business': '事業範囲',
	'business-content': 'BLM / BIMライフサイクル実装機能は、設計から構築、運用、保守管理までのライフサイクルソリューションを提供します。 メインストリームBIMプラットフォームに基づくソフトウェアの二次開発機能。 ',
	'municipal-engineering': '市営橋',
	'municipal-engineering-content': '為客戶提供市政橋樑BIM顧問，各種類型橋樑的BIM建模指導，輔助正向設計，從設計階段協助工程師，設計製造一體化。 ',
	'railway': '鐵路BIM',
	'railway-content': '基於中國鐵路規範，鐵路標準建模方法，提供標準模板庫，輔助正向設計，幫助客戶從傳統二維實現三維設計的轉變。 ',
	'building-facade': '建築幕牆',
	'building-facade-content': '為客戶提供前期建築方案諮詢，協助建立參數化模型,異型幕牆BIM諮詢，提供加工生產於製造數據，通過BIM技術協助現場施工放樣。 ',
	'projects-content': '我們的經驗主要在建築與市政工程領域，包含橋樑，道路與隧道.',
	'projects-all':'所有',
	'projects-title-bridge':'橋樑',
	'projects-title-tunnel':'隧道',
	'projects-title-railway':'鐵路',
	'projects-title-road':'道路',
	'projects-title-facade':'建築幕牆',
	'team-content': '團隊主要人員介紹',
	'general-manager': '總經理',
	'general-manager-content': '超過12年工作經驗，具有8年銷售經驗，現在擔任公司業務運行管理',
	'business-manager': '業務經理',
	'business-manager-content': '超過10年工作經驗，曾工作於建築設計單位，參與諸多大型商業建築項目，具有4年以上市政工程BIM項目實施經驗，同時擔任公司業務運行管理',
	'project-manager': '項目經理',
	'project-manager-content': '超過8年工作經驗，曾工作於建築設計單位，參與諸多複雜造型的建築立面設計，具有4年市政工程BIM項目實施經驗',
	'engineer': '工程師',
	'engineer-content': '超過3年工作經驗，擅長各種橋樑的參數化模型，配合橋樑設計師參與諸多項目設計過程',
	'software-development': '軟件開發',
	'software-development-content': '超過2年工作經驗，專注與3DEXPERIENCE CATIA軟件二次開發',
	'experience': '實踐經驗',
	'experience-project-content': '成功的項目實踐',
	'experience-partner-content': '友好的合作夥伴',
	'experience-base-on-3ds-content': '基於3DEXPERIENCE開發的軟件.',
	'experience-open-forums': 'www.3debim.com，開放的社區論壇，為客戶提供更好的交流平台',
	'dsbim-name':'上海迪賽信息技術有限公司',
	'dsbim-address':'中國上海市閔行區興虹路187弄2號協信中心1號樓202室 ',
	'dsbim-postnum':' 郵編:200333 ',
	'dsbim-mainemail':'電子郵件: support@ds-info.cn',
	'3dexperience-bim-forums':'3DEXPERIENCE BIM 論壇',
	'3dexperience-bim-forums-links': '3DEXPERIENCE BIM 論壇鏈接',
	'3dexperience-bim-forums-content':'通過郵箱註冊成為會員，即可提問，同時也歡迎發帖，交流技術！ ',
	'team-01':'王 利強',
	'team-02':'黨 剛',
	'team-03':'許 松',
	'team-04':'劉 迪',
	'team-05':'田 良',
	'team-06':'张 勇',
	'products-detail-content-hbd':'Highway Bridge Design (3DEXPERIENCE Native Apps Application)',
	'products-detail-content-hbd-content':'基於中國市政橋樑的設計特點，創建了標準模板庫，通過封裝獨立的APP調用模板庫，提高生成效率，定義易於使用的參數規則，快速導出數據。 ',
	'products-detail-content-rbd':'Railway Bridge Design (3DEXPERIENCE Native Apps Application)',
	'products-detail-content-rbd-content':'創建鐵路常用的模板，開發出橋樑布跨插件，可以快速防止上部結構與下部結構，同時快速導出數據以及導入數據更新模型。 ',
	'':''
    }
};

// Process translation
$(function() {
    $('.translate').click(function() {
    var lang = $(this).attr('id');

    $('.lang').each(function(index, item) {
        $(this).text(arrLang[lang][$(this).attr('key')]);
    });
    });
});
